# Topics
## 1) Indexing and slicing
## 2) Iterating through arrays
## 3) Stacking together two arrays
## 4) Indexing with boolean arrays
___

In [1]:
n = [4,5,6]
n[0:2]

[4, 5]

In [2]:
n[-1]

6

In [4]:
import numpy as np
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [5]:
n[-1]

6

In [6]:
a = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
a[1,2]

6

In [9]:
a[0:2,2]

array([3, 6])

In [10]:
a[-1]

array([6, 7, 8])

In [11]:
a[-1,0:2]

array([6, 7])

In [17]:
a[:,1:3]

array([[2, 3],
       [5, 6],
       [7, 8]])

In [19]:
a[:,2:3]

array([[3],
       [6],
       [8]])

In [22]:
a[:,2]

array([3, 6, 8])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [24]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[6 7 8]


In [25]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
6
7
8


In [40]:
x = np.arange(6).reshape(3,2)
y = np.arange(6,12).reshape(3,2)

In [41]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [42]:
y

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [44]:
# stack together vertically
np.vstack((x,y))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [45]:
# stack together horizontally
np.hstack((x,y))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [46]:
# slice big arrays into horizontal small arrays
a1 = np.arange(30).reshape(2,15)
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [53]:
result = np.hsplit(a1,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [54]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [55]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [57]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [60]:
# slice big arrays into vertical small arrays
result = np.vsplit(a1,2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [61]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [62]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

---

In [63]:
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
b = c > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
c[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [69]:
# any element that's greater than 4 replace with -1

c[b] = -1
c

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])