In [1]:
import numpy as np

In [2]:
a = np.array([5,6,9])
a[0]

5

In [3]:
a[1]

6

In [4]:
b = np.array([[1,2],[3,4],[5,6]])

In [15]:
# See the dimension
a.ndim

1

In [6]:
b.ndim

2

In [16]:
# size of a single item
b.itemsize

8

In [8]:
b.dtype

dtype('int64')

In [9]:
b = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [11]:
b.dtype

dtype('float64')

In [12]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [17]:
# size of elements or number of elements
b.size

6

In [19]:
# shape of the array
b.shape

(3, 2)

In [21]:
# array with all zeros
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# array with all ones
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
l = range(5)
l

range(0, 5)

In [24]:
l[1]

1

In [25]:
l[2]

2

In [26]:
l[5]

IndexError: range object index out of range

In [29]:
# range with numpy array
np.arange(1,5)

array([1, 2, 3, 4])

In [30]:
# range with steps
np.arange(1,5,2)

array([1, 3])

In [31]:
# linear number generate
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [33]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [36]:
c = np.array([[1,2],[2,3],[4,5]])
c

array([[1, 2],
       [2, 3],
       [4, 5]])

In [37]:
c.shape

(3, 2)

In [38]:
# Reshape function
c.reshape(2,3)

array([[1, 2, 2],
       [3, 4, 5]])

In [44]:
c.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [4],
       [5]])

In [45]:
# Reshape to flat
c.ravel()

array([1, 2, 2, 3, 4, 5])

In [46]:
c

array([[1, 2],
       [2, 3],
       [4, 5]])

In [47]:
# Minimum element
c.min()

1

In [49]:
# Maximum element
c.max()

5

In [53]:
# Sum elements
c.sum()

17

---
## ROW = AXIS 1, COLUMN = AXIS 0
---

In [57]:
c

array([[1, 2],
       [2, 3],
       [4, 5]])

In [55]:
# sum of columns
c.sum(axis = 0)

array([ 7, 10])

In [56]:
# sum of rows
c.sum(axis = 1)

array([3, 5, 9])

In [58]:
# square root
np.sqrt(c)

array([[1.        , 1.41421356],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798]])

In [59]:
# standard deviation
np.std(c)

1.3437096247164249

---
---

In [60]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [67]:
x

array([[1, 2],
       [3, 4]])

In [62]:
y

array([[5, 6],
       [7, 8]])

In [68]:
# sum of different arrays
x + y

array([[ 6,  8],
       [10, 12]])

In [69]:
# multiplication of different arrays
x * y

array([[ 5, 12],
       [21, 32]])

In [71]:
# division of different arrays
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [73]:
# matrics product of arrays
a.dot(b)

array([68., 88.])